In [1]:
import torch

### 2.2 数据操作

##### 2.2.1 创建tensor

In [2]:
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.6406, 0.9238, 0.0922],
        [0.6473, 0.6674, 0.1611],
        [0.5030, 0.4006, 0.9902],
        [0.9605, 0.9480, 0.8959],
        [0.1297, 0.1764, 0.9379]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [11]:
x = x.new_ones(5, 3, dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [15]:
x = x.new_ones(5, 3, dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x = torch.randn_like(x)
x

tensor([[-0.8039, -2.1062,  0.6247],
        [-0.2150, -1.1125, -1.0482],
        [ 1.4173,  0.4064, -0.9386],
        [-0.6430, -0.0637,  0.4733],
        [ 0.3752,  0.2650, -0.1538]], dtype=torch.float64)

In [18]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.4271,  0.1738,  0.8369],
        [-1.8467, -0.0908, -0.0407],
        [-0.1784, -0.3989, -2.4226],
        [-2.2788,  0.1421, -0.2225],
        [-0.4474, -1.3183, -1.7028]])

In [22]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


##### 2.2.2 操作

In [24]:
y = torch.rand(5, 3)
x + y 

tensor([[ 0.4629,  0.4597,  1.8158],
        [-1.0297, -0.0664,  0.7196],
        [ 0.8043,  0.1771, -2.2326],
        [-1.9421,  0.2714, -0.0827],
        [ 0.5044, -1.2272, -1.2797]])

In [25]:
torch.add(x, y)

tensor([[ 0.4629,  0.4597,  1.8158],
        [-1.0297, -0.0664,  0.7196],
        [ 0.8043,  0.1771, -2.2326],
        [-1.9421,  0.2714, -0.0827],
        [ 0.5044, -1.2272, -1.2797]])

In [26]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.4629,  0.4597,  1.8158],
        [-1.0297, -0.0664,  0.7196],
        [ 0.8043,  0.1771, -2.2326],
        [-1.9421,  0.2714, -0.0827],
        [ 0.5044, -1.2272, -1.2797]])

In [27]:
y.add_(x)
y

tensor([[ 0.4629,  0.4597,  1.8158],
        [-1.0297, -0.0664,  0.7196],
        [ 0.8043,  0.1771, -2.2326],
        [-1.9421,  0.2714, -0.0827],
        [ 0.5044, -1.2272, -1.2797]])

In [29]:
print(x[0, :])
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([0.5729, 1.1738, 1.8369])
tensor([1.5729, 2.1738, 2.8369])
tensor([1.5729, 2.1738, 2.8369])


In [30]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [32]:
x += 1
print(x)
print(y)
print(z)

tensor([[ 3.5729,  4.1738,  4.8369],
        [ 0.1533,  1.9092,  1.9593],
        [ 1.8216,  1.6011, -0.4226],
        [-0.2788,  2.1421,  1.7775],
        [ 1.5526,  0.6817,  0.2972]])
tensor([ 3.5729,  4.1738,  4.8369,  0.1533,  1.9092,  1.9593,  1.8216,  1.6011,
        -0.4226, -0.2788,  2.1421,  1.7775,  1.5526,  0.6817,  0.2972])
tensor([[ 3.5729,  4.1738,  4.8369,  0.1533,  1.9092],
        [ 1.9593,  1.8216,  1.6011, -0.4226, -0.2788],
        [ 2.1421,  1.7775,  1.5526,  0.6817,  0.2972]])


In [33]:
x_cp = x.clone().view(-1)
x -= 1
print(x)
print(x_cp)

tensor([[ 2.5729,  3.1738,  3.8369],
        [-0.8467,  0.9092,  0.9593],
        [ 0.8216,  0.6011, -1.4226],
        [-1.2788,  1.1421,  0.7775],
        [ 0.5526, -0.3183, -0.7028]])
tensor([ 3.5729,  4.1738,  4.8369,  0.1533,  1.9092,  1.9593,  1.8216,  1.6011,
        -0.4226, -0.2788,  2.1421,  1.7775,  1.5526,  0.6817,  0.2972])


In [36]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9673])
-0.9672794342041016


##### 2.2.3 广播机制

In [39]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


##### 2.2.4 运算的内存开销

In [40]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [41]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [42]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


##### 2.2.5 Tensor和numpy相互转换

In [43]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [44]:
a += 1
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [45]:
b += 1
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [46]:
c = torch.tensor(a)
a += 1
print(a, c)

tensor([4., 4., 4., 4., 4.]) tensor([3., 3., 3., 3., 3.])


/Users/dongdong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


##### 2.2.6 Tensor On GPU

In [48]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("cuda is not available")

cuda is not available


### 2.3 自动求梯度

##### 2.3.1 概念

* Tensor
    - requires_grad
    - backward()
    - grad
    - detach() / with torch.no_grad()
    - grad_fn

* Function
    - Tensor和Function互相结合就可以构建⼀一个记录有整个计算过 程的有向⽆无环图(DAG)

##### 2.3.2 Tensor

In [49]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [50]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [51]:
print(x.is_leaf, y.is_leaf)

True False


In [52]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [55]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.grad_fn)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

None
False
True


##### 2.3.2 梯度

In [56]:
out.backward()
# d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [57]:
out2 = x.sum()
print(out2)

tensor(4., grad_fn=<SumBackward0>)


In [58]:
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [59]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [62]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [63]:
v = torch.tensor([[1.0, 0.1],[0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [71]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [72]:
y3.backward()
print(x.grad)

tensor(2.)
